=== btnguyen2k/btnguyen2k-personal/ptngoc-gsc/trunk/portal-module.dtd
<!ELEMENT portal-module (module-info, module-properties?, portlets?, languages?, templates?, action-mapping, pages?)>
<!ATTLIST portal-module
	name CDATA #REQUIRED
	brief-description CDATA #IMPLIED>

<!ELEMENT module-info (description, version, portal-version, vendor)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT version EMPTY>
<!ATTLIST version
	number CDATA #REQUIRED
	build CDATA #IMPLIED
	date CDATA #IMPLIED>
<!ELEMENT portal-version EMPTY>
<!ATTLIST portal-version
	min CDATA #IMPLIED
	max CDATA #IMPLIED>
<!ELEMENT vendor EMPTY>
<!ATTLIST vendor
	name CDATA #REQUIRED
	url CDATA #IMPLIED>

<!ELEMENT module-properties (property*)>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property
	name ID #REQUIRED>

<!ELEMENT portlets (portlet*)>
<!ELEMENT portlet EMPTY>
<!ATTLIST portlet
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	class CDATA #REQUIRED>
	
<!ELEMENT languages EMPTY>
<!ATTLIST languages
	registry CDATA #REQUIRED>
	
<!ELEMENT templates EMPTY>
<!ATTLIST templates
	registry CDATA #REQUIRED>

<!ELEMENT action-mapping (default-handler?, default-view?, module*)>

<!ELEMENT module (form*, default-handler?, default-view?, handler*, view*)>
<!ATTLIST module
	name ID #REQUIRED>

<!ELEMENT form (form-property*)>
<!ATTLIST form
	name ID #REQUIRED
	validatorClass CDATA #IMPLIED>
	
<!ELEMENT form-property EMPTY>
<!ATTLIST form-property
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	required (true|false) "true"
	default-value CDATA #IMPLIED
	max-length CDATA #IMPLIED
	min-length CDATA #IMPLIED
	min-value CDATA #IMPLIED
	max-value CDATA #IMPLIED
	allowed-values CDATA #IMPLIED
	pattern CDATA #IMPLIED>

<!ELEMENT default-handler EMPTY>
<!ATTLIST default-handler
	class CDATA #REQUIRED>

<!ELEMENT handler EMPTY>
<!ATTLIST handler
	class CDATA #REQUIRED
	action CDATA #REQUIRED
	form IDREF #IMPLIED>

<!ELEMENT default-view EMPTY>
<!ATTLIST default-view
	class CDATA #REQUIRED>

<!ELEMENT view EMPTY>
<!ATTLIST view
	class CDATA #REQUIRED
	action CDATA #REQUIRED>
	
<!ELEMENT pages (page*)>
<!ELEMENT page ((layout|disabled-location)+)>
<!ATTLIST page
	action CDATA #REQUIRED>
<!ELEMENT layout EMPTY>
<!ATTLIST layout
	location CDATA #REQUIRED
	portlet CDATA #REQUIRED
	position CDATA #REQUIRED>
<!ELEMENT disabled-location EMPTY>
<!ATTLIST disabled-location
	id CDATA #REQUIRED>

=== btnguyen2k/btnguyen2k-personal/ptngoc-gsc/trunk/portal-module.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  
<!DOCTYPE portal-module PUBLIC 
	"-//DDTH.ORG//DTD Portal Module//EN"
	"portal-module.dtd">
-->
<portal-module name="gsc" brief-description="Greenstorm Card">
	<!-- Module information -->
	<module-info>
		<description>GreenStorm Card</description>
		<version number="1.0.0" build="0" date="200910131213" />
		<portal-version min="1.0" max="1.0" />
		<vendor name="DDTH" url="http://www.ddth.org" />
	</module-info>

	<!--  
	<module-properties>
		<property name="txbb.seoUnicode">org.ddth.txbb.util.TCVN6909SeoUnicode</property>
		<property name="txbb.txCodeParser">org.ddth.txbb.util.XhtmlTXCodeParser</property>
	</module-properties>
	-->

	<portlets>
		<!--  
		<portlet name="txbb_admin_mainmenu" description="TXBB's Administrative Main Menu"
			class="org.ddth.txbb.portlets.admin.MainMenuPortlet" />
		<portlet name="txbb_mainmenu" description="TXBB's non-Administrative Main Menu"
			class="org.ddth.txbb.portlets.MainMenuPortlet" />
		<portlet name="txbb_personalcorner" description="TXBB's Personal Corner Menu"
			class="org.ddth.txbb.portlets.PersonalCornerPortlet" />
		-->
	</portlets>

	<languages registry="/languages/registry.xml"></languages>

	<templates registry="/templates/registry.xml"></templates>

	<action-mapping>
		<module name="gsc">
			<form name="frmBoxCreate">
				<form-property name="parentId" type="java.lang.Integer" />
				<form-property name="title" type="java.lang.String"
					required="true" max-length="255" />
				<form-property name="outerDescription" type="java.lang.String"
					required="false" />
				<form-property name="innerDescription" type="java.lang.String"
					required="false" />
			</form>

			<form name="frmBoxEdit">
				<form-property name="parentId" type="java.lang.Integer" />
				<form-property name="title" type="java.lang.String"
					required="true" max-length="255" />
				<form-property name="outerDescription" type="java.lang.String"
					required="false" />
				<form-property name="innerDescription" type="java.lang.String"
					required="false" />
			</form>

			<form name="frmBoxDelete">
			</form>

			<form name="frmTopicCreate">
				<form-property name="topicType" type="java.lang.String"
					required="true" allowed-values="question,article,information" />
			</form>

			<form name="frmTopicEdit">
				<form-property name="topicType" type="java.lang.String"
					required="true" allowed-values="question,article,information" />
				<form-property name="topicTitle" type="java.lang.String"
					max-length="255" />
				<form-property name="topicContent" type="java.lang.String" />
			</form>

			<form name="frmTopicDelete">
			</form>

			<form name="frmTopicPublish">
				<form-property name="publishedBoxes" type="java.lang.Integer[]"
					required="false" />
			</form>

			<form name="frmTopicUnpublish">
			</form>

			<form name="frmTopicLock">
			</form>

			<form name="frmTopicUnlock">
			</form>

			<default-handler class="com.greenstorm.gsc.panda.DefaultHandler" />

			<default-view
				class="org.ddth.panda.portal.module.core.panda.DefaultViewRenderer" />

			<handler action="index" class="com.greenstorm.gsc.panda.IndexHandler" />
		</module>
	</action-mapping>

	<pages>
		<page action="_">
			<!--
			<layout location="TOP" portlet="portal_topmenubar" position="-1" />
			<layout location="LEFT" portlet="txbb_mainmenu" position="-2" />
			<layout location="LEFT" portlet="txbb_personalcorner"
				position="-1" />
			<layout location="LEFT" portlet="portal_loginreminder"
				position="-1" />			

			<layout location="BOTTOM" portlet="portal_bottommenubar"
				position="-2" />
			<layout location="BOTTOM" portlet="portal_systeminfo"
				position="-1" />
			-->
		</page>
	</pages>
</portal-module>
